# -*- coding: utf-8 -*-
"""social_distancing_config.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5dGyLDlwomVOvzJpqJHCV_8qjfVfQgz
"""

# base path to YOLO directory
MODEL_PATH = "yolo-coco"
# initialize minimum probability to filter weak detections along with
# the threshold when applying non-maxima suppression
MIN_CONF = 0.3
NMS_THRESH = 0.3
# boolean indicating if NVIDIA CUDA GPU should be used
USE_GPU = False
# define the minimum safe distance (in pixels) that two people can be
# from each other
MIN_DISTANCE = 50